@echo off
cd /d "%~dp0.."
echo Import monitor assets...
"vendor dashboard\.venv\Scripts\python.exe" tools\import_monitor_assets.py
echo Relabel all monitor images...
"vendor dashboard\.venv\Scripts\python.exe" tools\relabel_class_dataset.py monitor
echo Validate...
"vendor dashboard\.venv\Scripts\python.exe" tools\validate_yolo_dataset.py
if errorlevel 1 exit /b 1
echo Training (monitor-focused fine-tune)...
"vendor dashboard\.venv\Scripts\python.exe" tools\train_yolov8.py --epochs 80 --imgsz 640 --batch 8 --name genspark_monitor
pause
